// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://heasdwqqitapschdhirz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlYXNkd3FxaXRhcHNjaGRoaXJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0ODQwNTcsImV4cCI6MjA1ODA2MDA1N30.vgS7p5aMU33SgTIyZpIYBlEOE2dbpY3wM09bBCiplTE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);